## 总结

## 全局变量

### const

1. 常量在程序中定义时必须也被赋值

```go
const (	
 // 不会报错 B C默认使用A的值
 A = 'A'
 // 沿用上一个变量的值
 B 
 C
)

const (	
 // 报错 
 A 
 B = 'B'
 C
)

```

### iota

1. iota：在const块中与const连用

2. iota默认为0

3. **iota相当于const语句中的行索引**

4. 对于新建的const语句 使用iota时索引会重新变为0

   ```go
   const (
   	A = iota // 0 下一行应该为1
       B // 1
       C // 2
   )
   const D = iota // 重新变为0 
   const E = iota // 重新变为0
   ```

5. 使用`_`忽略某一生成的计数器值

   ```go
   const (
   	_ = iota
       b // 1
       c // 2
       _ // 3
       e // 4
   )
   ```

6. iota插队

   ```go
   const (
   	A = iota // 0
       B 		 // 1
       C = 100  // 100
       // 此时iota还在自增 但是D的值也上方的字面值常量为准 不会自增了
       D 
       // 若要恢复 则需要再次显示iota
       // 此时还在原来的const代码块中 iota不会重新计数
       E = iota // 4
   )
   ```

### var

1. 通过var来定义全局变量

2. var定义变量后可以不赋值 不赋值的话则为默认值

3. 局部变量优于全局变量

   

## 执行顺序

> 关于defer和panic的文章 https://mp.weixin.qq.com/s/INzvMdnWc8K4mnbV3R4Mrw

### panic

> [(60条消息) Go面试：从一道判断题来谈panic和defer的调用机制和执行顺序_pengpengzhou的博客-CSDN博客_panic和defer顺序](https://blog.csdn.net/pengpengzhou/article/details/107663338)

1. panic 会退出当前正在执行的程序(注意，不只是 *Go*routine *协程*)

2. 子函数中的`panic`函数不会传递到父函数中

3. `panic`之后的`defer`语句不会被执行 因为还没将该defer中的内容加入到该协程存放`defer`的链表中

4. 在`defer`中使用`panic`

   ```go
   func main(){
       defer func() {
           panic("panic1")
   	}()
   	defer func() {
   		panic("panic2")
   	}()
   	defer func() {
   		panic("panic3")
   	}()
   	panic("panic")
   }
   
   // 输出
   panic: panic
   panic: panic3
   panic: panic2
   panic: panic1
   
   ```

 5. 在`defer`中使用`recover`捕获`panic`

    ```go
    func main(){
        defer func() {
    		if err := recover(); err != nil {
    			fmt.Println(err)
    		}
    	}()
        
        defer func() {
            panic("panic1")
    	}()
    	defer func() {
    		panic("panic2")
    	}()
    	defer func() {
    		panic("panic3")
    	}()
    	panic("panic")
    }
    
    // 输出
    panic1
    ```

6. 运行时`panic`

   1. 运行时错误也会导致`panic` 例如数组越界 等价于调用内置函数panic

   2. panic发生的场景
      - 数组/切片越界
      - 空指针调用
      - 除以0
      - 向已经关闭的管道发送数据
      - 重复关闭管道
      - 关闭未初始化的管道
      - 未初始化map
      - 类型断言不匹配

   

### recover

1. **`recover` 不能恢复一个不同协程的 panic**

   ```go
   func recovery() {
       if r := recover(); r != nil {
           fmt.Println("recovered:", r)
       }
   }
   
   func a() {
       // 在a中
       defer recovery()
       fmt.Println("Inside A")
       // 新开协程b
       go b()
       time.Sleep(1 * time.Second)
   }
   
   func b() {
       fmt.Println("Inside B")
       // 没有defer
       // 没有recover 直接退出该进程
       panic("oh! B panicked")
   }
   
   func main() {
       a()
       fmt.Println("normally returned from main")
   }
   
   // 输出
   Inside A
   Inside B
   panic: oh! B panicked
   ```


### defer



## 控制语句

1. IF的判断条件只能是bool类型，而不是nil或者非nil，1或0
2. 对map的循环遍历中，for-range中的k,v代表map中的键值

## 数值类型

1. 对浮点型赋值整数 不会出错

   ```go
   var f float64 = 1
   fmt.Println(f) // 输出1
   ```

2. **对整数型赋值小数不为0的浮点数** 会出错

   ```go
   // '1.88' (type untyped float) cannot be represented by the type int64
   var f int64 = 1.88
   fmt.Println(f)
   
   // 不会出错，输出1
   var i int = 1.00
   fmt.Println(i)
   ```

3. 字符串中的单引号和双引号

   1. 通过单引号定义的变量实际上是rune(int32)类型，单引号里面是单个字符

   2. 通过双引号定义的变量实际上是字符串，双引号中可以有`转义`字符，如\n,\r等

   3. 通过反引号定义的字符串，表示其原生的意思，在反引号中的内容可以是**多行**内容，**不支持转义**

      ```go
      func main() {
          a := `Hello golang\n:
      I am random_wz.
      Good.`
          fmt.Println(a)
      }
      
      // 输出
      $ go run main.go
      Hello golang\n:
      I am random_wz.
      Good.
      ```

      

## 包的初始化

1. 对导入的包进行递归初始化

   ![](C:\Users\zyb\AppData\Roaming\Typora\typora-user-images\image-20221030172632705.png)

2. 每个源文件可以包含多个`init`函数

3. `init`函数没有被声明，而不能被引用

   ```go
   func init() {
   	fmt.Println("init")
   }
   
   func main() {
    	init() // 编译出错，undefined: init
   }
   ```

## 函数声明

1. 若函数有多个返回值，要么对全部返回值都命名，要么都不命名

   ```go
   func test(a int, b int) (value int, err error)
   func test(a int, b int) (int, error)
   
   // 错误写法
   func test(a int, b int) (value int, error)
   ```
